# Generated by Django 6.0.3 on 2026-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. 128 символа', max_length=128, unique=True, verbose_name='Ингредиент')),
                ('measurement_unit', models.PositiveSmallIntegerField(help_text='Макс. 64 символов', max_length=64, verbose_name='Единица измерения')),
            ],
        ),
    ]
