# Generated by Django 6.0.3 on 2026-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Макс. 64 символов', max_length=64, verbose_name='Единица измерения'),
        ),
    ]
