# Generated by Django 6.0.3 on 2026-03-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='test',
            new_name='text',
        ),
    ]
