# Generated by Django 6.0.3 on 2026-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_test_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes.images', verbose_name='Изображение рецепта'),
        ),
    ]
