# Generated by Django 6.0.3 on 2026-04-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favorite_shoppingcart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart',
        ),
    ]
