# Generated by Django 6.0.3 on 2026-04-05 09:03

from django.db import migrations, models

import users.models.custom_user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=users.models.custom_user.get_user_avatar_path, verbose_name='Аватар'),
        ),
    ]
