# Generated by Django 6.0.3 on 2026-04-05 09:22

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], regex='[\\w.@+-]+\\z')], verbose_name='Имя пользователя'),
        ),
    ]
