# Generated by Django 6.0.3 on 2026-04-05 09:31

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
